/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modelo;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Clariss
 */
public class inicio extends javax.swing.JFrame {
    Diccionario d = new Diccionario();
    public static HashSet<Palabra> palabrasRefinadas = new HashSet<Palabra>();
    public static LinkedList<Palabra> lista = new LinkedList<Palabra>();
        
    public ArrayList<Documento> docs;
    public Documento consulta;
    
    public inicio() {
        try {
            initComponents();
            palabrasRefinadas = d.listaPalabras();
            for (Palabra palabra : palabrasRefinadas) {
                lista.add(palabra);
            }
            Collections.sort(lista);
            Iterator<Palabra> iterador = lista.listIterator();
            while (iterador.hasNext()) {
                Palabra p = iterador.next();
                docs = p.getDocumentos();
                System.out.print(p.getNombre());
                for (Documento doc  : docs) {
                    if(doc.getRepeticiones()>0){
                        System.out.print("  "+doc.getNombre()+"-"+doc.getRepeticiones());
                    }
                }
                System.out.println();
            }
        } catch (IOException ex) {
            Logger.getLogger(inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonBooleano = new javax.swing.JButton();
        botonVectorial = new javax.swing.JButton();
        botonProbabilistico = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonBooleano.setText("Modelo Booleano");
        botonBooleano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBooleanoActionPerformed(evt);
            }
        });

        botonVectorial.setText("Modelo Vectorial");
        botonVectorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVectorialActionPerformed(evt);
            }
        });

        botonProbabilistico.setText("Modelo Probabilistico");
        botonProbabilistico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonProbabilisticoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cambria", 1, 14)); // NOI18N
        jLabel1.setText("Modelos de Recuperacion de la Información");

        jLabel2.setText("Seleccione un Modelo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 51, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(94, 94, 94)
                            .addComponent(botonProbabilistico, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(botonVectorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonBooleano, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(botonBooleano)
                .addGap(18, 18, 18)
                .addComponent(botonVectorial)
                .addGap(18, 18, 18)
                .addComponent(botonProbabilistico)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBooleanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBooleanoActionPerformed
        
        Booleano mBool = new Booleano();
        mBool.setVisible(true);
       this.setVisible(false);
                
    }//GEN-LAST:event_botonBooleanoActionPerformed

    private void botonVectorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVectorialActionPerformed
        // TODO add your handling code here:
        Vectorial mVec = new Vectorial();
        mVec.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_botonVectorialActionPerformed

    private void botonProbabilisticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonProbabilisticoActionPerformed
        // TODO add your handling code here:
        Probabilistico mProb = new Probabilistico();
        mProb.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_botonProbabilisticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBooleano;
    private javax.swing.JButton botonProbabilistico;
    private javax.swing.JButton botonVectorial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
